apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: security-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongodb-storage
            mountPath: /data/db
        command: [ "mongod", "--quiet", "--logpath", "/dev/null", "--bind_ip_all" ]
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: security-scanner
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
