apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-analyzer
  namespace: security-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-analyzer
  template:
    metadata:
      labels:
        app: static-analyzer
    spec:
      containers:
      - name: static-analyzer
        # Replace with your Docker Hub image
        image: saaf20/static-analyzer:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: static-analyzer
  namespace: security-scanner
spec:
  selector:
    app: static-analyzer
  ports:
    - port: 5003
      targetPort: 5003
      protocol: TCP
      name: http
